Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg
between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Pandas Questions
5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```
6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```
7. How to get the rows of a dataframe with row sum > 100?

Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [6]:
import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[7, 8, 9],[1, 2, 3]])

stacked_vertically = np.vstack((A, B))
stacked_horizontally = np.hstack((A, B))

In [7]:
stacked_vertically

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [8]:
stacked_horizontally

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 1, 2, 3]])

2. Find common elements between A and B. [Hint : Intersection of two sets]

In [9]:
common_elements = np.intersect1d(A, B)
common_elements

array([1, 2, 3])

3. Extract all numbers from A which are within a specific range. eg
between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [11]:
lower_bound = 5
upper_bound = 10
numbers_in_range = A[np.where((A >= lower_bound) & (A <= upper_bound))]
numbers_in_range

array([5, 6])

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Pandas Questions
5. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [16]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


6. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())


print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


7. How to get the rows of a dataframe with row sum > 100?

In [20]:
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [21]:
filtered_df = df[(df['Min.Price'] + df['Max.Price']) > 100]
print(filtered_df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
58       43.8       80.0


In [23]:
df_numeric = df.apply(pd.to_numeric, errors='coerce')
filtered_df_2 = df_numeric[df_numeric.sum(axis=1) > 100]
print(filtered_df_2)

    Manufacturer  Model  Type  Min.Price  Price  Max.Price  MPG.city  \
0            NaN    NaN   NaN  12.900000   15.9  18.800000      25.0   
1            NaN    NaN   NaN  29.200000   33.9  38.700000      18.0   
2            NaN   90.0   NaN  25.900000   29.1  32.300000      20.0   
3            NaN  100.0   NaN  17.118605   37.7  44.600000      19.0   
4            NaN    NaN   NaN  17.118605   30.0  21.459091      22.0   
..           ...    ...   ...        ...    ...        ...       ...   
88           NaN    NaN   NaN  16.600000   19.7  22.700000      17.0   
89           NaN    NaN   NaN  17.600000   20.0  22.400000      21.0   
90           NaN    NaN   NaN  22.900000   23.3  23.700000      18.0   
91           NaN  240.0   NaN  21.800000   22.7  23.500000      21.0   
92           NaN  850.0   NaN  24.800000   26.7  28.500000      20.0   

    MPG.highway  AirBags  DriveTrain  ...  Passengers  Length  Wheelbase  \
0          31.0      NaN         NaN  ...         5.0   177